# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: aca7455b52fe32f9b8169dc448eec76ef15386d5887ef77110bf2a6a1e762e37eadf6c4b8e29fba4cbcc9b172250cc9ff48ed6eed0303fbf8e1724062a1a6b61

test:
  secret_key_base: 0edf0b779c60b4b608d81ff597ee34a58e40aa0d15899be7fe78b396cdc643bd99bc20fa1d19c0ce21b62a1c756c52b3dc3ef6dc9b4e3eea10a6b91c15d026a9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
